### ISSUE TITLE
Could you tell me the number of hits in my repo?

### ISSUE THREAD

**Issue by silentsoft** [dwyl/hits#121]
I hope to see your amazing `hits.dwyl.com` again but still the 502 goes on.. 😭 

If you don't mind, I'd like to know how many hits my repo has. 🙏 

Here is the query 😆 

```sql
SELECT A.hits, B.name
  FROM (SELECT COUNT(*) AS hits, repo_id
          FROM hits
         WHERE 1=1
           AND repo_id IN (SELECT id
                             FROM repositories
                            WHERE 1=1 
                              AND user_id = (SELECT id
                                               FROM users
                                              WHERE 1=1
                                                AND name = 'silentsoft'))
         GROUP BY repo_id) A, repositories B
 WHERE 1=1
   AND A.repo_id = B.id;
```

Thanks,

**Comment by SimonLab** [comment]
Hi @silentsoft I'm not sure if your repositories still use this hits as you have now created yours (https://github.com/silentsoft/hits) but here are your hits for the repositories we have in our database:

slack-api:   [![HitCount](http://hits.dwyl.com/silentsoft/slack-api.svg?style=flat-square)](http://hits.dwyl.com/silentsoft/slack-api)
arguments-parser: [![HitCount](http://hits.dwyl.com/silentsoft/arguments-parser.svg?style=flat-square)](http://hits.dwyl.com/silentsoft/arguments-parser)
 actlist:   [![HitCount](http://hits.dwyl.com/silentsoft/actlist.svg?style=flat-square)](http://hits.dwyl.com/silentsoft/actlist)
 actlist-plugin-starter-kit   [![HitCount](http://hits.dwyl.com/silentsoft/actlist-plugin-starter-kit.svg?style=flat-square)](http://hits.dwyl.com/silentsoft/actlist-plugin-starter-kit)
pushbullet-api:   [![HitCount](http://hits.dwyl.com/silentsoft/pushbullet-api.svg?style=flat-square)](http://hits.dwyl.com/silentsoft/pushbullet-api)

Let us know if you have any other questions otherwise feel free to close this issue :+1:
